# Generated by Django 4.1.3 on 2022-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('technical_name', models.CharField(max_length=10, unique=True, verbose_name='Technical name')),
            ],
        ),
    ]
