# Generated by Django 4.1.3 on 2023-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_fr',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
