# Generated by Django 4.1.3 on 2022-12-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('demo_link', models.URLField(default='https://example.com', help_text='The demo link to access it.', max_length=150, verbose_name='Demo link')),
                ('github_link', models.CharField(default='https://github.com', help_text='The Github account URL.', max_length=150, verbose_name='Github link')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='media', verbose_name='Image')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_category.projectcategory', verbose_name='Category')),
            ],
        ),
    ]
