# Generated by Django 4.1.3 on 2023-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_fr',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
