# Generated by Django 4.1.3 on 2023-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(default='My job is to build your website...', help_text='A little description of this experience.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(default='My job is to build your website...', help_text='A little description of this experience.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fr',
            field=models.TextField(default='My job is to build your website...', help_text='A little description of this experience.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_en',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_es',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_fr',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
