# Generated by Django 4.1.3 on 2022-11-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Github link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LinkedIn link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Short description',
        ),
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.CharField(default='https://github.com', help_text='The Github account URL.', max_length=120, verbose_name='Github link'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.CharField(default='https://linkedin.com', help_text='The LinkedIn account URL.', max_length=120, verbose_name='LinkedIn link'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.TextField(default='Add a little description...', help_text='The short description adding below the title.', verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Define a description here...', help_text='The description adding to about me section.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Image'),
        ),
    ]
