# Generated by Django 4.1.3 on 2023-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description_en',
            field=models.TextField(default='Define a description here...', help_text='The description adding to about me section.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='description_fr',
            field=models.TextField(default='Define a description here...', help_text='The description adding to about me section.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description_en',
            field=models.TextField(default='Add a little description...', help_text='The short description adding below the title.', null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description_fr',
            field=models.TextField(default='Add a little description...', help_text='The short description adding below the title.', null=True, verbose_name='Short description'),
        ),
    ]
