# Generated by Django 4.1.3 on 2022-11-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='Is display in website'),
        ),
    ]
