# Generated by Django 4.1.3 on 2022-11-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_user_is_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', upload_to='media', verbose_name='Logo'),
        ),
    ]
