# Generated by Django 4.1.3 on 2022-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_image_alter_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='01/01/1990', help_text='The birthday display in the website', max_length=10, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='San Francisco - United States', help_text='The location display in the website.', max_length=40, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_email',
            field=models.EmailField(default='example@example.com', help_text='The email display in the website.', max_length=40, verbose_name='Professional email'),
        ),
    ]
