# Generated by Django 4.1.3 on 2023-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(default='Define a description for this skill.', help_text='The description about the current skill.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fr',
            field=models.TextField(default='Define a description for this skill.', help_text='The description about the current skill.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
